[dependencies.color-eyre]
workspace = true

[dependencies.rayon]
workspace = true

[dependencies.common]
workspace = true

[package]
edition = "2021"
name = "day_2"
version = "0.1.0"

[[bin]]
name = "day_2_task_1"
path = "src/task_one.rs"

[[bin]]
name = "day_2_task_2"
path = "src/task_two.rs"
