[workspace]
members = ["day_1", "common"]
resolver = "2"

[workspace.dependencies]

clap = { version = "4.4.10", features = ["derive"] }
common = { path = "common" }
rayon = { version = "1.5.1", features = [] }
color-eyre = "0.6.2"
